spring:
  data:
    redis:
      host: localhost
      port: 6379
  application:
    name: guildaApi
  cache:
      type: redis
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password123
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  sql:
    init:
      mode: always
      continue-on-error: true
  elasticsearch:
    uris: http://localhost:9200
