-- aventura.aventureiros definition

-- Drop table

-- DROP TABLE aventura.aventureiros;

CREATE TABLE IF NOT EXISTS aventura.aventureiros (
                                       id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                       ativo bool NOT NULL,
                                       classe varchar(255) NOT NULL,
                                       created_at timestamptz DEFAULT now() NOT NULL,
                                       nivel int4 NOT NULL,
                                       nome varchar(120) NOT NULL,
                                       updated_at timestamptz DEFAULT now() NOT NULL,
                                       organizacao_id int8 NOT NULL,
                                       usuario_responsavel_id int8 NOT NULL,
                                       CONSTRAINT aventureiros_classe_check CHECK (((classe)::text = ANY ((ARRAY['GUERREIRO'::character varying, 'MAGO'::character varying, 'ARQUEIRO'::character varying, 'CLERIGO'::character varying, 'LADINO'::character varying])::text[]))),
	CONSTRAINT aventureiros_nivel_check CHECK ((nivel >= 1)),
	CONSTRAINT aventureiros_pkey PRIMARY KEY (id)
);


-- aventura.companheiros definition

-- Drop table

-- DROP TABLE aventura.companheiros;

CREATE TABLE IF NOT EXISTS aventura.companheiros (
                                       id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                       especie varchar(255) NOT NULL,
                                       indice_lealdade int4 NOT NULL,
                                       nome varchar(120) NOT NULL,
                                       aventureiro_id int8 NOT NULL,
                                       CONSTRAINT companheiros_especie_check CHECK (((especie)::text = ANY ((ARRAY['LOBO'::character varying, 'CORUJA'::character varying, 'GOLEM'::character varying, 'DRAGAO_MINIATURA'::character varying])::text[]))),
	CONSTRAINT companheiros_indice_lealdade_check CHECK (((indice_lealdade <= 100) AND (indice_lealdade >= 0))),
	CONSTRAINT companheiros_pkey PRIMARY KEY (id),
	CONSTRAINT ukfy265twqh973hn315ww5qry7h UNIQUE (aventureiro_id)
);


-- aventura.missoes definition

-- Drop table

-- DROP TABLE aventura.missoes;

CREATE TABLE IF NOT EXISTS aventura.missoes (
                                  id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                  created_at timestamptz DEFAULT now() NOT NULL,
                                  data_inicio timestamptz(6) NULL,
                                  data_termino timestamptz(6) NULL,
                                  nivel_de_perigo varchar(255) NOT NULL,
                                  status varchar(255) NOT NULL,
                                  titulo varchar(150) NOT NULL,
                                  organizacao_id int8 NOT NULL,
                                  CONSTRAINT missoes_nivel_de_perigo_check CHECK (((nivel_de_perigo)::text = ANY ((ARRAY['BAIXO'::character varying, 'MEDIO'::character varying, 'ALTO'::character varying, 'EXTREMO'::character varying])::text[]))),
	CONSTRAINT missoes_pkey PRIMARY KEY (id),
	CONSTRAINT missoes_status_check CHECK (((status)::text = ANY ((ARRAY['PLANEJADA'::character varying, 'EM_ANDAMENTO'::character varying, 'CONCLUIDA'::character varying, 'CANCELADA'::character varying])::text[])))
);


-- aventura.participacao_em_missoes definition

-- Drop table

-- DROP TABLE aventura.participacao_em_missoes;

CREATE TABLE IF NOT EXISTS aventura.participacao_em_missoes (
                                                  id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                                  data_registro timestamptz DEFAULT now() NOT NULL,
                                                  destaque_mvp bool NOT NULL,
                                                  papel_na_missao varchar(255) NOT NULL,
                                                  recompensa_em_ouro int4 NULL,
                                                  aventureiro_id int8 NOT NULL,
                                                  missao_id int8 NOT NULL,
                                                  CONSTRAINT participacao_em_missoes_papel_na_missao_check CHECK (((papel_na_missao)::text = ANY ((ARRAY['SUPORTE'::character varying, 'ATAQUE'::character varying, 'DEFESA'::character varying, 'CURANDEIRO'::character varying, 'EXPLORADOR'::character varying, 'LIDER'::character varying])::text[]))),
	CONSTRAINT participacao_em_missoes_pkey PRIMARY KEY (id),
	CONSTRAINT participacao_em_missoes_recompensa_em_ouro_check CHECK ((recompensa_em_ouro >= 0)),
	CONSTRAINT uq_participacao_aventureiro_missao UNIQUE (aventureiro_id, missao_id)
);


-- aventura.aventureiros foreign keys

ALTER TABLE aventura.aventureiros ADD CONSTRAINT fk69bghwq8ernvslk6qyf6my51u FOREIGN KEY (usuario_responsavel_id) REFERENCES audit.usuarios(id);
ALTER TABLE aventura.aventureiros ADD CONSTRAINT fkiy6fyy3d7aywlxksmrlwpee4x FOREIGN KEY (organizacao_id) REFERENCES audit.organizacoes(id);


-- aventura.companheiros foreign keys

ALTER TABLE aventura.companheiros ADD CONSTRAINT fk82rquuffeqqsljw7e8t70v9v6 FOREIGN KEY (aventureiro_id) REFERENCES aventura.aventureiros(id);


-- aventura.missoes foreign keys

ALTER TABLE aventura.missoes ADD CONSTRAINT fkqosuw2x9lphdr180gpnnnkfwb FOREIGN KEY (organizacao_id) REFERENCES audit.organizacoes(id);


-- aventura.participacao_em_missoes foreign keys

ALTER TABLE aventura.participacao_em_missoes ADD CONSTRAINT fk21w2d7vsr9d0eyq50wpquktao FOREIGN KEY (missao_id) REFERENCES aventura.missoes(id);
ALTER TABLE aventura.participacao_em_missoes ADD CONSTRAINT fktl3pkk7h2ky29wdhbt2s0ab91 FOREIGN KEY (aventureiro_id) REFERENCES aventura.aventureiros(id);